name: app_t_shop
description: 'A new Flutter project.'

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3



#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter
    
  # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.0
  connectivity_plus: ^6.0.3
  lottie: ^3.1.0 # OR RIVE
  fluttertoast: ^8.0.9

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.4
  google_sign_in: ^6.2.1
#  flutter_facebook_auth: ^3.5.0





  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Font MB Bank
      fonts:
        - asset: assets/fonts/Intelligent Design - AvertaStdCY-Light.otf
          weight: 300
        - asset: assets/fonts/Intelligent Design - AvertaStdCY-Regular.otf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Intelligent Design - AvertaStdCY-Bold.otf
          weight: 500
        - asset: assets/fonts/Intelligent Design - AvertaStdCY-BoldItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Intelligent Design - AvertaStdCY-Bold.otf
          weight: 600
        - asset: assets/fonts/Intelligent Design - AvertaStdCY-Extrabold.otf
          weight: 800
