// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYX3v7gg703gYsNIzuQQEsfNvmgzodWog',
    appId: '1:1086094493399:web:d2a10e4967c84d17149292',
    messagingSenderId: '1086094493399',
    projectId: 'ecommerceapp-tshop',
    authDomain: 'ecommerceapp-tshop.firebaseapp.com',
    storageBucket: 'ecommerceapp-tshop.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArDp9OoNX4SA7GApViGVJWQwSdrOzS18w',
    appId: '1:1086094493399:android:f6356706ce0eaa98149292',
    messagingSenderId: '1086094493399',
    projectId: 'ecommerceapp-tshop',
    storageBucket: 'ecommerceapp-tshop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIL-ff3UnlmT3YlK2lSsMQazSNBqCn5j0',
    appId: '1:1086094493399:ios:7111d6059e0b56be149292',
    messagingSenderId: '1086094493399',
    projectId: 'ecommerceapp-tshop',
    storageBucket: 'ecommerceapp-tshop.appspot.com',
    androidClientId: '1086094493399-f8rjl1510a2e9e632e99h9i2s8e4dcce.apps.googleusercontent.com',
    iosClientId: '1086094493399-tr7u6v9n0h7tkpeisfj0bbfh623oo0bf.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIL-ff3UnlmT3YlK2lSsMQazSNBqCn5j0',
    appId: '1:1086094493399:ios:7111d6059e0b56be149292',
    messagingSenderId: '1086094493399',
    projectId: 'ecommerceapp-tshop',
    storageBucket: 'ecommerceapp-tshop.appspot.com',
    androidClientId: '1086094493399-f8rjl1510a2e9e632e99h9i2s8e4dcce.apps.googleusercontent.com',
    iosClientId: '1086094493399-tr7u6v9n0h7tkpeisfj0bbfh623oo0bf.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYX3v7gg703gYsNIzuQQEsfNvmgzodWog',
    appId: '1:1086094493399:web:c3a36cb0c93bb407149292',
    messagingSenderId: '1086094493399',
    projectId: 'ecommerceapp-tshop',
    authDomain: 'ecommerceapp-tshop.firebaseapp.com',
    storageBucket: 'ecommerceapp-tshop.appspot.com',
  );

}